# ??? ?? ??
server:
  port: 8761

# ??? ?? ??
spring:
  application:
    name: discovery-service

# ??? ?? ??
eureka:
  server:
    enable-self-preservation: true # ???? ?? ? ??? ??? ?? ?? ????
  client:
    register-with-eureka: false # ??? ????, ?? ??? ??? ?????? ????
    fetch-registry: false # ??? ????, ??? ??? ????? ?? ???? ??

# End Poitn ??
management:
  endpoints:
    web:
      exposure:
        include: "*"
